import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import ToasterContext from './context/ToasterContext';
import AuthContext from './context/AuthContext';
import { Providers } from '@/store/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Messenger App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthContext>
                    <Providers>
                        <ToasterContext />
                        {children}
                    </Providers>
                </AuthContext>
            </body>
        </html>
    );
}
